from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

def make_pdf(path: str = "sample.pdf"):
    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4

    # 제목
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 80, "KNU MLA - Short PDF")

    # 본문 (여러 줄)
    c.setFont("Helvetica", 12)
    y = height - 120
    lines = [
        "This is a short PDF generated by Python.",
        "You can add text, lines, and shapes easily.",
        "ReportLab is great for quick PDFs.",
    ]
    for line in lines:
        c.drawString(50, y, line)
        y -= 18

    # 선/박스
    c.line(50, y - 10, width - 50, y - 10)
    c.rect(50, y - 80, width - 100, 60)

    c.save()

if __name__ == "__main__":
    make_pdf("sample.pdf")
