import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/components/layout/language-context";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/components/auth-provider";
<<<<<<< HEAD
import { BackgroundWrapper } from "@/components/layout/background-wrapper";
=======

import { BackgroundProvider } from "@/components/layout/background-provider";
>>>>>>> 3f9535c0ba0d1465d120ac478de5798047cd6ca3

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <LanguageProvider>
<<<<<<< HEAD
              <BackgroundWrapper />
              {children}
=======
              <BackgroundProvider>
                {children}
              </BackgroundProvider>
>>>>>>> 3f9535c0ba0d1465d120ac478de5798047cd6ca3
            </LanguageProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
